//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionGuard.UI.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectionGuard.UI.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally has been canceled by election administrator. See administrator for addional details..
        /// </summary>
        internal static string AbandonTallyText {
            get {
                return ResourceManager.GetString("AbandonTallyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally Canceled.
        /// </summary>
        internal static string AbandonTallyTitle {
            get {
                return ResourceManager.GetString("AbandonTallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ballots.
        /// </summary>
        internal static string AddBallots {
            get {
                return ResourceManager.GetString("AddBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string AddedText {
            get {
                return ResourceManager.GetString("AddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home.
        /// </summary>
        internal static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Do You Want To Do?.
        /// </summary>
        internal static string AdminHomePageTitle {
            get {
                return ResourceManager.GetString("AdminHomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.  Try a different name..
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupText {
            get {
                return ResourceManager.GetString("BackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Verification.
        /// </summary>
        internal static string BadVerified {
            get {
                return ResourceManager.GetString("BadVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string BallotCountText {
            get {
                return ResourceManager.GetString("BallotCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot Folder.
        /// </summary>
        internal static string BallotFolderText {
            get {
                return ResourceManager.GetString("BallotFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballots.
        /// </summary>
        internal static string BallotsText {
            get {
                return ResourceManager.GetString("BallotsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot Styles.
        /// </summary>
        internal static string BallotStylesText {
            get {
                return ResourceManager.GetString("BallotStylesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot Upload.
        /// </summary>
        internal static string BallotUploadText {
            get {
                return ResourceManager.GetString("BallotUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        internal static string CandidatesText {
            get {
                return ResourceManager.GetString("CandidatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the verification code in the search box to limit the ballots shown. Select that ballot from the list to be set to a spoiled ballot..
        /// </summary>
        internal static string ChallengedInstructionsText {
            get {
                return ResourceManager.GetString("ChallengedInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        internal static string ChallengedText {
            get {
                return ResourceManager.GetString("ChallengedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        internal static string ChoiceText {
            get {
                return ResourceManager.GetString("ChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File(s).
        /// </summary>
        internal static string ChooseFiles {
            get {
                return ResourceManager.GetString("ChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Folder.
        /// </summary>
        internal static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string to get to database.
        /// </summary>
        internal static string ConnectionStringPlaceholder {
            get {
                return ResourceManager.GetString("ConnectionStringPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        internal static string ConnectionStringText {
            get {
                return ResourceManager.GetString("ConnectionStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the election administrator!.
        /// </summary>
        internal static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        internal static string ContestsText {
            get {
                return ResourceManager.GetString("ContestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CreatedByText {
            get {
                return ResourceManager.GetString("CreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string CreatedText {
            get {
                return ResourceManager.GetString("CreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Election.
        /// </summary>
        internal static string CreateElection {
            get {
                return ResourceManager.GetString("CreateElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Key Ceremony.
        /// </summary>
        internal static string CreateKeyCeremony {
            get {
                return ResourceManager.GetString("CreateKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the elections to make tallies.
        /// </summary>
        internal static string CreateMultiInstructionsText {
            get {
                return ResourceManager.GetString("CreateMultiInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Tallies.
        /// </summary>
        internal static string CreateMultipleTalliesText {
            get {
                return ResourceManager.GetString("CreateMultipleTalliesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Tallies.
        /// </summary>
        internal static string CreateMultiTally {
            get {
                return ResourceManager.GetString("CreateMultiTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Key Ceremonies that are used for multi-tallies.
        /// </summary>
        internal static string CreateMultiTallyError {
            get {
                return ResourceManager.GetString("CreateMultiTallyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tallies.
        /// </summary>
        internal static string CreateTallies {
            get {
                return ResourceManager.GetString("CreateTallies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tally.
        /// </summary>
        internal static string CreateTally {
            get {
                return ResourceManager.GetString("CreateTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Range for Ballot Selection.
        /// </summary>
        internal static string CustomRangeText {
            get {
                return ResourceManager.GetString("CustomRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database IP Address.
        /// </summary>
        internal static string DatabaseAddress {
            get {
                return ResourceManager.GetString("DatabaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login.  Please check your database settings..
        /// </summary>
        internal static string DatabaseLoginError {
            get {
                return ResourceManager.GetString("DatabaseLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Password.
        /// </summary>
        internal static string DatabasePassword {
            get {
                return ResourceManager.GetString("DatabasePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not available. Please check your settings..
        /// </summary>
        internal static string DatabaseUnavailable {
            get {
                return ResourceManager.GetString("DatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string DatesText {
            get {
                return ResourceManager.GetString("DatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Decryption Complete.
        /// </summary>
        internal static string DecryptionComplete {
            get {
                return ResourceManager.GetString("DecryptionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device File.
        /// </summary>
        internal static string DeviceFileText {
            get {
                return ResourceManager.GetString("DeviceFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string DevicesText {
            get {
                return ResourceManager.GetString("DevicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Exist.
        /// </summary>
        internal static string DoesNotExist {
            get {
                return ResourceManager.GetString("DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGDrive already used.
        /// </summary>
        internal static string DriveUsedText {
            get {
                return ResourceManager.GetString("DriveUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated.
        /// </summary>
        internal static string DuplicatedText {
            get {
                return ResourceManager.GetString("DuplicatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Checklist.
        /// </summary>
        internal static string ElectionChecklist {
            get {
                return ResourceManager.GetString("ElectionChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Details.
        /// </summary>
        internal static string ElectionDetails {
            get {
                return ResourceManager.GetString("ElectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectionGuard.
        /// </summary>
        internal static string ElectionGuardTitle {
            get {
                return ResourceManager.GetString("ElectionGuardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Name.
        /// </summary>
        internal static string ElectionNameText {
            get {
                return ResourceManager.GetString("ElectionNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Record Export Path.
        /// </summary>
        internal static string ElectionRecordPathText {
            get {
                return ResourceManager.GetString("ElectionRecordPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elections created..
        /// </summary>
        internal static string ElectionsCreated {
            get {
                return ResourceManager.GetString("ElectionsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elections.
        /// </summary>
        internal static string ElectionsText {
            get {
                return ResourceManager.GetString("ElectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election URL.
        /// </summary>
        internal static string ElectionUrl {
            get {
                return ResourceManager.GetString("ElectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating election.
        /// </summary>
        internal static string ErrorCreatingElection {
            get {
                return ResourceManager.GetString("ErrorCreatingElection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load guardian data..
        /// </summary>
        internal static string ErrorLoadingGuardian {
            get {
                return ResourceManager.GetString("ErrorLoadingGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest file could not be loaded..
        /// </summary>
        internal static string ErrorLoadingManifest {
            get {
                return ResourceManager.GetString("ErrorLoadingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Error Logs.
        /// </summary>
        internal static string ErrorLogs {
            get {
                return ResourceManager.GetString("ErrorLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in manifest files.
        /// </summary>
        internal static string ErrorManifest {
            get {
                return ResourceManager.GetString("ErrorManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the EGDrive removable storage is connected to the device. Please note, this will replace any encryption package currently on all EGDrive devices.
        /// </summary>
        internal static string ExportDriveWarning {
            get {
                return ResourceManager.GetString("ExportDriveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Encryption Package.
        /// </summary>
        internal static string ExportDriveWarningTitle {
            get {
                return ResourceManager.GetString("ExportDriveWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Encryption.
        /// </summary>
        internal static string ExportEncryptionText {
            get {
                return ResourceManager.GetString("ExportEncryptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Election Record.
        /// </summary>
        internal static string ExportTally {
            get {
                return ResourceManager.GetString("ExportTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geopolitical Units.
        /// </summary>
        internal static string GeopoliticalUnitsText {
            get {
                return ResourceManager.GetString("GeopoliticalUnitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Key Ceremony.
        /// </summary>
        internal static string GoToCreateKeyCeremonyAdmin {
            get {
                return ResourceManager.GetString("GoToCreateKeyCeremonyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Home.
        /// </summary>
        internal static string GuardianHome {
            get {
                return ResourceManager.GetString("GuardianHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardians.
        /// </summary>
        internal static string GuardiansText {
            get {
                return ResourceManager.GetString("GuardiansText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to import from this EGDrive again?.
        /// </summary>
        internal static string ImportAgainText {
            get {
                return ResourceManager.GetString("ImportAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an EGDrive (USB drive) containing ballots.
        /// </summary>
        internal static string InsertUsbText {
            get {
                return ResourceManager.GetString("InsertUsbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address of the database.
        /// </summary>
        internal static string IPAddressPlaceholder {
            get {
                return ResourceManager.GetString("IPAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Guardians.
        /// </summary>
        internal static string JoinedGuardians {
            get {
                return ResourceManager.GetString("JoinedGuardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined.
        /// </summary>
        internal static string JoinedText {
            get {
                return ResourceManager.GetString("JoinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tallies to join.
        /// </summary>
        internal static string JoinMultiInstructionsText {
            get {
                return ResourceManager.GetString("JoinMultiInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Tallies.
        /// </summary>
        internal static string JoinTallies {
            get {
                return ResourceManager.GetString("JoinTallies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ceremonies.
        /// </summary>
        internal static string KeyCeremoniesText {
            get {
                return ResourceManager.GetString("KeyCeremoniesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ceremony Name.
        /// </summary>
        internal static string KeyCeremonyName {
            get {
                return ResourceManager.GetString("KeyCeremonyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ceremony State.
        /// </summary>
        internal static string KeyCeremonyState {
            get {
                return ResourceManager.GetString("KeyCeremonyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Ceremony.
        /// </summary>
        internal static string KeyCeremonyText {
            get {
                return ResourceManager.GetString("KeyCeremonyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationText {
            get {
                return ResourceManager.GetString("LocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name or other identifier.
        /// </summary>
        internal static string LoginPlaceholder {
            get {
                return ResourceManager.GetString("LoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest.
        /// </summary>
        internal static string ManifestText {
            get {
                return ResourceManager.GetString("ManifestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel wizard and manually upload ballots.
        /// </summary>
        internal static string ManuelUploadText {
            get {
                return ResourceManager.GetString("ManuelUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiTally Name.
        /// </summary>
        internal static string MultiTallyNameText {
            get {
                return ResourceManager.GetString("MultiTallyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names will be generated from manifest names.
        /// </summary>
        internal static string NameFromManifest {
            get {
                return ResourceManager.GetString("NameFromManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue with the network that caused an issue with what you were doing.  Please log back in when the network connection has been restored.
        /// </summary>
        internal static string NetworkIssueText {
            get {
                return ResourceManager.GetString("NetworkIssueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ballots Uploaded.
        /// </summary>
        internal static string NoBallotUploads {
            get {
                return ResourceManager.GetString("NoBallotUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elections found.
        /// </summary>
        internal static string NoElections {
            get {
                return ResourceManager.GetString("NoElections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        internal static string NoFileText {
            get {
                return ResourceManager.GetString("NoFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder chosen.
        /// </summary>
        internal static string NoFolderText {
            get {
                return ResourceManager.GetString("NoFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guardians joined.
        /// </summary>
        internal static string NoGuardians {
            get {
                return ResourceManager.GetString("NoGuardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key ceremonies found.
        /// </summary>
        internal static string NoKeyCeremonies {
            get {
                return ResourceManager.GetString("NoKeyCeremonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tallies found.
        /// </summary>
        internal static string NoTallies {
            get {
                return ResourceManager.GetString("NoTallies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tallies Created.
        /// </summary>
        internal static string NoTalliesCreated {
            get {
                return ResourceManager.GetString("NoTalliesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Guardians.
        /// </summary>
        internal static string NumberOfGuardians {
            get {
                return ResourceManager.GetString("NumberOfGuardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties.
        /// </summary>
        internal static string PartiesText {
            get {
                return ResourceManager.GetString("PartiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string PartyText {
            get {
                return ResourceManager.GetString("PartyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to use for the database.
        /// </summary>
        internal static string PasswordDefaultPlaceholder {
            get {
                return ResourceManager.GetString("PasswordDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Admin to Announce the Guardians.
        /// </summary>
        internal static string PendingAdminAnnounce {
            get {
                return ResourceManager.GetString("PendingAdminAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Admin to Create and Publish the Joint Key.
        /// </summary>
        internal static string PendingAdminToPublishJointKey {
            get {
                return ResourceManager.GetString("PendingAdminToPublishJointKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Admin to Share the Election Key Backups.
        /// </summary>
        internal static string PendingAdminToShareBackups {
            get {
                return ResourceManager.GetString("PendingAdminToShareBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the Guardians to Backup Election Keys.
        /// </summary>
        internal static string PendingGuardianBackups {
            get {
                return ResourceManager.GetString("PendingGuardianBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Guardians to Join.
        /// </summary>
        internal static string PendingGuardianJoin {
            get {
                return ResourceManager.GetString("PendingGuardianJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Guardians to Verify the Backups.
        /// </summary>
        internal static string PendingGuardiansVerifyBackups {
            get {
                return ResourceManager.GetString("PendingGuardiansVerifyBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string PercentText {
            get {
                return ResourceManager.GetString("PercentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detected.
        /// </summary>
        internal static string PreviousCrash {
            get {
                return ResourceManager.GetString("PreviousCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Tally.
        /// </summary>
        internal static string ProcessTallyAbandon {
            get {
                return ResourceManager.GetString("ProcessTallyAbandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Do not Join Tally.
        /// </summary>
        internal static string ProcessTallyJoinNo {
            get {
                return ResourceManager.GetString("ProcessTallyJoinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Join Tally.
        /// </summary>
        internal static string ProcessTallyJoinYes {
            get {
                return ResourceManager.GetString("ProcessTallyJoinYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tally.
        /// </summary>
        internal static string ProcessTallyStartTally {
            get {
                return ResourceManager.GetString("ProcessTallyStartTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quorum.
        /// </summary>
        internal static string Quorum {
            get {
                return ResourceManager.GetString("Quorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quorum.
        /// </summary>
        internal static string QuorumText {
            get {
                return ResourceManager.GetString("QuorumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RejectedText {
            get {
                return ResourceManager.GetString("RejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing files from the list.
        /// </summary>
        internal static string RemovingList {
            get {
                return ResourceManager.GetString("RemovingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian has responded to Admin Challenge.
        /// </summary>
        internal static string ResponseComplete {
            get {
                return ResourceManager.GetString("ResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsText {
            get {
                return ResourceManager.GetString("ResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Challenge.
        /// </summary>
        internal static string ReviewSpoiledText {
            get {
                return ResourceManager.GetString("ReviewSpoiledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Elections.
        /// </summary>
        internal static string SelectAllElectionsText {
            get {
                return ResourceManager.GetString("SelectAllElectionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection one or more manifest files.
        /// </summary>
        internal static string SelectManifest {
            get {
                return ResourceManager.GetString("SelectManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Challenged to Spoiled.
        /// </summary>
        internal static string SpoilBallotText {
            get {
                return ResourceManager.GetString("SpoilBallotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoil Ballots.
        /// </summary>
        internal static string SpoilChallengedText {
            get {
                return ResourceManager.GetString("SpoilChallengedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you would like to move this ballot into a Spoiled state?  This will remove it from the election record..
        /// </summary>
        internal static string SpoilConfirmationText {
            get {
                return ResourceManager.GetString("SpoilConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoiled.
        /// </summary>
        internal static string SpoiledText {
            get {
                return ResourceManager.GetString("SpoiledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Ceremony.
        /// </summary>
        internal static string StartCeremony {
            get {
                return ResourceManager.GetString("StartCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the encryption package.
        /// </summary>
        internal static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ballots using EGDrive (1 or more).
        /// </summary>
        internal static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Challenge Ballots (if needed).
        /// </summary>
        internal static string Step3Text {
            get {
                return ResourceManager.GetString("Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a tally with the guardians (1 or more).
        /// </summary>
        internal static string Step4Text {
            get {
                return ResourceManager.GetString("Step4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and export a tally.
        /// </summary>
        internal static string Step5Text {
            get {
                return ResourceManager.GetString("Step5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ballots..
        /// </summary>
        internal static string Success2Text {
            get {
                return ResourceManager.GetString("Success2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded.
        /// </summary>
        internal static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Languages.
        /// </summary>
        internal static string SwitchLanguages {
            get {
                return ResourceManager.GetString("SwitchLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallies.
        /// </summary>
        internal static string TalliesText {
            get {
                return ResourceManager.GetString("TalliesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Guardians responded to Challenge.
        /// </summary>
        internal static string TallyAllChallengesResponded {
            get {
                return ResourceManager.GetString("TallyAllChallengesResponded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Guardian Shares Calculated.
        /// </summary>
        internal static string TallyAllDecryptionsComputed {
            get {
                return ResourceManager.GetString("TallyAllDecryptionsComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge Created.
        /// </summary>
        internal static string TallyChallengeCreated {
            get {
                return ResourceManager.GetString("TallyChallengeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally Process.
        /// </summary>
        internal static string TallyChecklist {
            get {
                return ResourceManager.GetString("TallyChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally Verified and results computed.
        /// </summary>
        internal static string TallyComplete {
            get {
                return ResourceManager.GetString("TallyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally Name.
        /// </summary>
        internal static string TallyNameText {
            get {
                return ResourceManager.GetString("TallyNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally Process.
        /// </summary>
        internal static string TallyProcess {
            get {
                return ResourceManager.GetString("TallyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quorum has been reached.
        /// </summary>
        internal static string TallyQuorumReachedText {
            get {
                return ResourceManager.GetString("TallyQuorumReachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballots have been tallied.
        /// </summary>
        internal static string TallySubtalliesCombined {
            get {
                return ResourceManager.GetString("TallySubtalliesCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally.
        /// </summary>
        internal static string TallyText {
            get {
                return ResourceManager.GetString("TallyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalText {
            get {
                return ResourceManager.GetString("TotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string UploadedText {
            get {
                return ResourceManager.GetString("UploadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload More Ballots.
        /// </summary>
        internal static string UploadMoreText {
            get {
                return ResourceManager.GetString("UploadMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadText {
            get {
                return ResourceManager.GetString("UploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Wizard.
        /// </summary>
        internal static string UploadWizardText {
            get {
                return ResourceManager.GetString("UploadWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use All Ballots For Tally.
        /// </summary>
        internal static string UseAllBallotsText {
            get {
                return ResourceManager.GetString("UseAllBallotsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setup.
        /// </summary>
        internal static string UserSetup {
            get {
                return ResourceManager.GetString("UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        internal static string VerificationCodeText {
            get {
                return ResourceManager.GetString("VerificationCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Key Ceremony.
        /// </summary>
        internal static string ViewKeyCeremony {
            get {
                return ResourceManager.GetString("ViewKeyCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that something went wrong.  You can contine with what you were doing before this happened.  Details are available in the log files in the Settings page..
        /// </summary>
        internal static string ViewLogsText {
            get {
                return ResourceManager.GetString("ViewLogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Manifest.
        /// </summary>
        internal static string ViewManifest {
            get {
                return ResourceManager.GetString("ViewManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Tally.
        /// </summary>
        internal static string ViewTally {
            get {
                return ResourceManager.GetString("ViewTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string VotesText {
            get {
                return ResourceManager.GetString("VotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElectionGuard Election Manager.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writein Candidate.
        /// </summary>
        internal static string WriteinText {
            get {
                return ResourceManager.GetString("WriteinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive contains ballots for a different election..
        /// </summary>
        internal static string WrongElectionText {
            get {
                return ResourceManager.GetString("WrongElectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
