name: Pull Request UI Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/pull-request-ui.yml"
      - "src/electionguard-ui/**"
    branches: [main]

env:
  TARGET: Release

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: ["macOS", "windows-os"]
        include:
          - name: macOS
            os: macOS-12
            version: "14.1"
            osFolder: "maccatalyst"
          - name: windows-os
            os: windows-2022
            version: "latest"
            osFolder: "windows"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Update Mac Environment
        if: runner.os == 'macOS'
        run: |
          ls -ls /Applications/
          ls -ls $ANDROID_SDK_ROOT/ndk
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
      - name: Configure Environment
        run: make environment-ui
      - name: Clean UI
        run: make clean-ui
      - name: Publish UI
        run: make publish-ui BUILD=${{ github.run_number }}
      - name: save build artifacts
        uses: actions/upload-artifact@v3

        with:
          name: electionguard-ui-${{ matrix.name }}
          retention-days: 7
          path: |
            ${{ github.workspace}}/src/electionguard-ui/ElectionGuard.UI/bin/${{ env.TARGET }}/**/*.pkg
            ${{ github.workspace}}/src/electionguard-ui/ElectionGuard.UI/bin/${{ env.TARGET }}/**/ElectionGuard.UI*.msix
