name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/electionguard-ui/**"
    branches: [main]

env:
  TARGET: Release

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          [
            "ubuntu-22.04-clang-14.0.0",
            "ubuntu-22.04-gcc-12.1.0",
            "macos-12-xcode-14.1",
            "macos-12-xcode-14.1-arm64",
            "windows-2022-gcc-11",
            "windows-2022-msvc-latest",
            "ubuntu-22.04-linter",
          ]
        include:
          - name: ubuntu-22.04-clang-14.0.0
            os: ubuntu-22.04
            processor: x64
            compiler: clang
            version: "14"
            makeReleaseBuild: false
            lint: false
            runCsTests: false
          - name: ubuntu-22.04-gcc-12.1.0
            os: ubuntu-22.04
            processor: x64
            compiler: gcc
            version: "12"
            makeReleaseBuild: false
            lint: false
            runCsTests: false
          - name: macOS-12-xcode-14.1
            os: macOS-12
            processor: x64
            compiler: xcode
            version: "14.1"
            makeReleaseBuild: false
            lint: false
            runCsTests: true
          - name: macOS-12-xcode-14.1-arm64
            os: macOS-12
            processor: arm64
            compiler: xcode
            version: "14.1"
            makeReleaseBuild: false
            lint: false
            runCsTests: false
          - name: windows-2022-gcc-11
            os: windows-2022
            processor: x64
            compiler: gcc
            version: "11"
            makeReleaseBuild: false
            lint: false
            runCsTests: false
          - name: windows-2022-msvc-latest
            os: windows-2022
            processor: x64
            compiler: msvc
            version: "latest"
            makeReleaseBuild: false
            lint: false
            runCsTests: true
          - name: ubuntu-22.04-linter
            os: ubuntu-22.04
            processor: x64
            compiler: clang
            version: "14"
            makeReleaseBuild: false
            lint: true
            runCsTests: true

    steps:
      - run: 'echo "No build required"'
