name: Pull Request UI Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/pull-request-ui.yml"
      - "src/electionguard-ui/**"
    branches: [main]

env:
  TARGET: Release

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: ["macOS", "windows-os"]
        include:
          - name: macOS
            os: macOS-12
            version: "14.1"
            osFolder: "maccatalyst"
          - name: windows-os
            os: windows-2022
            version: "latest"
            osFolder: "windows"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Update Mac Environment
        if: runner.os == 'macOS'
        run: |
          ls -ls /Applications/
          ls -ls $ANDROID_SDK_ROOT/ndk
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
      - name: Configure Environment
        run: make environment
      - name: Rebuild
        run: make rebuild-ui
      - name: Test
        run: make test-ui
      - name: save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electionguard-ui-${{ matrix.name }}
          retention-days: 7
          path: |
            src/electionguard-ui/bin/${{ env.TARGET }}/**/*.{pkg,msix}
          if-no-files-found: error
