name: Run Sanitizer
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "apps/**"
      - "bindings/**"
      - "include/**"
      - "src/**"
      - "test/**"
#  schedule:
#    - cron: '0 0 * * 2-6' Daily at 00:00 UTC Tuesday-saturday

env:
  TARGET: Release
  compiler: clang

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if non Linux OS
        if: runner.os != 'Linux'
        run: exit 1
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update Environment
        run: |
          echo "compiler_version=$(echo | clang -dM -E - | grep __clang_version__ | tail -1 |  grep -o ' "[0-9]*' | sed 's/ "//g')" >> $GITHUB_ENV
          echo "CC=clang-${{ env.compiler_version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ env.compiler_version }}" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y clang-${{ env.compiler_version }} g++-multilib
      - name: Configure Environment
        run: make environment
      - name: Run Tests
        run: make test
      - name: Run .Net Tests
        run: make test-netstandard

      - name: Run Sanitizer
        run: make sanitize-asan # TODO: Add other sanitizers
      - name: Run Benchmarks
        run: make bench
