name: Run Sanitizer
on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "bindings/**"
      - "include/**"
      - "src/**"
      - "!src/electionguard-ui/**"
      - "test/**"
#  schedule:
#    - cron: '0 0 * * 2-6' Daily at 00:00 UTC Tuesday-saturday

env:
  TARGET: Release
  compiler: clang
  compiler_version: "14"

jobs:
  Test:
    runs-on: ubuntu-22.04

    steps:
      - name: Fail if non Linux OS
        if: runner.os != 'Linux'
        run: exit 1
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Update Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-${{ env.compiler_version }} g++-multilib
          echo "CC=clang-${{ env.compiler_version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ env.compiler_version }}" >> $GITHUB_ENV
      - name: Configure Environment
        run: make environment
      - name: Build
        run: make build
      - name: Run Tests
        run: make test
      - name: Run .Net Tests
        run: make test-netstandard
      - name: Run Benchmarks
        run: make bench
      - name: Run Sanitizer
        run: make sanitize-asan # TODO: Add other sanitizers
